### ISSUE TITLE
DISCLAIMER padding

### ISSUE THREAD

**Issue by chadbunn** [SLUGIS/performanceMeasures#16]
how do I shrink the padding on the disclaimer???

**Comment by tstan** [comment]
I don't know if this is already solved but if you mean the extra space on the hover text box, I see you gave the text an "h6" attribute so you could add something like 

```
h6 {
    display: block;
    font-size: .67em;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: 0;
    margin-right: 0;
    font-weight: bold;
}
```

to your CSS style and play around with the margins

**Comment by chadbunn** [comment]
this solved it! nice work
